import packageJson from "../package.json";
import {
  FaReact,
  FaNodeJs,
  FaJava,
  FaPhp,
  FaPython,
  FaHtml5,
  FaCss3Alt,
  FaGitAlt,
  FaAndroid,
} from "react-icons/fa";

import {
  SiTypescript,
  SiTailwindcss,
  SiNextdotjs,
  SiMongodb,
  SiPostgresql,
  SiFlask,
  SiSolidity,
  SiSharp,
  SiFirebase,
  SiRedis,
  SiGraphql,
  SiDocker,
  SiSpringboot,
  SiLaravel,
  SiBootstrap,
  SiStreamlit,
  SiPytorch,
  SiKotlin,
  SiMysql,
} from "react-icons/si";

export const navItems = [
  { name: "Home", path: "/" },
  { name: "Experience", path: "/experience" },
  { name: "Projects", path: "/projects" },
  { name: "Blog", path: "/blog" },
  { name: "Contact", path: "/#contact" },
];

export const techStackMap: Record<string, string> = {
  React: "react",
  TypeScript: "typescript",
  TailwindCSS: "tailwindcss",
  "Node.js": "nodejs",
  NextJS: "nextjs",
  aws: "aws",
  MongoDB: "mongodb",
  PostgreSQL: "postgresql",
  Python: "python",
  Flask: "flask",
  Solidity: "solidity",
  "C#": "csharp",
  Firebase: "firebase",
  "AWS IoT": "aws",
  AWS: "aws",
  "C++": "c++",
  Azure: "azure",
  Redis: "redis",
  GraphQL: "graphql",
  Docker: "docker",
  Java: "java",
  MySQL: "mysql",
  Spring: "spring",
  "Spring Boot": "spring",
  Git: "git",
  GitLab: "gitlab",
  Android: "android",
  Kotlin: "kotlin",
  "TensorFlow Lite": "python",
  SQLite: "mysql",
  TensorFlow: "",
  Matplotlib: "",
  "Google Colab": "colab",
  Laravel: "laravel",
  PHP: "php",
  Bootstrap: "bootstrap5",
  Blade: "laravel",
  Streamlit: "streamlit",
  Pytorch: "pytorch",
};

export const appVersion = packageJson.version;
